### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by neutrinoq** [ThisIsHwang/EXIT#1]
Hi, thanks for the great work! I am interested in your pipeline and want to follow your direction. It would be great if you could open-source your code and provide a guideline. Thank you for your attention on this issue!

**Comment by ThisIsHwang** [comment]
Thanks for your interest in our work! We're excited to share that we've just released a quickstart guide and the model weights as an initial step. You can find:

A complete quickstart example at [quickstart.py](https://github.com/ThisIsHwang/EXIT/blob/main/quickstart.py)
Pre-trained model weights at [doubleyyh/exit-gemma-2b](https://huggingface.co/doubleyyh/exit-gemma-2b)

This should help you get started with the EXIT pipeline right away. We're working on releasing the full training code and will update the repository soon. Feel free to open new issues if you have any questions about the current implementation!
Best regards,
Authors
